
import React, { useEffect, useState } from 'react'
export default function Reporting(){
  const [tx,setTx]=useState([]); const [query,setQuery]=useState(''); const [from,setFrom]=useState(''); const [to,setTo]=useState('')
  useEffect(()=>{ fetch('http://localhost:5000/api/transactions').then(r=>r.json()).then(setTx) },[])
  const filtered = tx.filter(t=> (t.productId||'').toLowerCase().includes(query.toLowerCase()) || (t.customerId||'').toLowerCase().includes(query.toLowerCase()) ).filter(t=> { if(from && t.date<from) return false; if(to && t.date>to) return false; return true })
  const exportSales = ()=>{ fetch('http://localhost:5000/api/export/sales').then(r=>r.text()).then(txt=>{ const blob=new Blob([txt],{type:'text/csv'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='sales.csv'; a.click() }) }
  const printReport = ()=>{ const rows = filtered.map(t=>`<tr><td>${t.date}</td><td>${t.productId}</td><td>${t.qty}</td><td>${t.type}</td></tr>`).join(''); const win=window.open('','_blank'); win.document.write('<html><head><title>Report</title><style>table{width:100%;border-collapse:collapse}td,th{border:1px solid #ccc;padding:6px}</style></head><body>'); win.document.write('<h3>Wings Cafe - Transactions Report</h3>'); win.document.write('<table><thead><tr><th>Date</th><th>Product</th><th>Qty</th><th>Type</th></tr></thead><tbody>'+rows+'</tbody></table>'); win.document.write('</body></html>'); win.document.close(); win.print() }
  return (<div><h2>Reporting</h2><div style={{display:'flex',gap:8,alignItems:'center'}}><input placeholder="Search productId or customerId" value={query} onChange={e=>setQuery(e.target.value)} /><label>From: <input type="date" value={from} onChange={e=>setFrom(e.target.value)} /></label><label>To: <input type="date" value={to} onChange={e=>setTo(e.target.value)} /></label><button onClick={exportSales}>⬇️ Export Sales CSV</button><button onClick={printReport}>🖨️ Print Report</button></div><table className="table"><thead><tr><th>Date</th><th>Product</th><th>Qty</th><th>Type</th></tr></thead><tbody>{filtered.map(t=>(<tr key={t.id}><td>{t.date}</td><td>{t.productId}</td><td>{t.qty}</td><td>{t.type}</td></tr>))}</tbody></table></div>)
}
